### ISSUE TITLE
Add Structured Data Records to All Steps

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-salesforce#66]
## What / Why
In order to help users diagnose failed test scenarios, we should add structured step response data that helps "show" the underlying information used in the step.

## Scope / UAT Target
- [ ] Step Updates (see [this example from the Pardot Cog](https://github.com/run-crank/cog-pardot/commit/5208f7b6a43cc6b27be3afbefae70ec1d9935ef8)):
  - [x] **Object Create/Delete Steps** - All object create and delete steps (`account`, `contact`, `lead`, and `opportunity`) should include KeyValue structured data responses that conform to the following specs:
    - [x] `id` should be `${objectName} (e.g. `lead`)
    - [x] `name` should be `Created|Deleted ${objectName}` (e.g. `Created Lead`
    - [x] Fields returned should only ever include an `Id` field.
  - [ ] **Object Check Steps**
    - [ ] KeyValue Records: All object check steps (`account`, `campaignMember`, `contact`, `lead`, and `opportunity`) should include KeyValue structured data responses that conform to the following specs:
      - [ ] `id` should be `${objectName} (e.g. `campaignMember`)
      - [ ] `name` should be `Checked ${objectName}` (e.g. `Checked Campaign Member`
      - [ ] Fields returned on the ExpectedRecords definition should always include the following fields: `Id`, `CreatedDate`, `LastModifiedDate`.
      - [ ] In order to support the above, the `findObjectByField()` methods for each object type should be updated to no longer specify field names to return at query-time (so that all fields are always returned).
    - [ ] Table Records: All objects where identifiers must be provided to query for objects to check (e.g. `Opportunity` and `Account`) should return a Table record in cases where multiple objects matched the given search criteria.  Each row in the table should match the schema for the equivalent KeyValue record.

## Proposed Resolution
- [x] Update the Cog protobuf definition and built files
  - [x] The `cog.proto` should be updated to [the version released in Crank v0.9.0](https://github.com/run-crank/cli/blob/v0.9.0/src/assets/proto/cog.proto)
  - [x] The Cog protobuffer and gRPC protobuffer scripts (and typings) should be updated to [the versions released in Crank v0.9.0](https://github.com/run-crank/cli/tree/v0.9.0/src/proto)
- [x] Update core cog classes/interfaces (see [this example from the Pardot Cog](https://github.com/run-crank/cog-pardot/commit/088a5d92f67139357ce02cd6d97daae33a4e126c))
  - [x] There should be three new protected methods on the BaseStep class, which return the three types of structured data records:
    - [x] For objects: `keyValue(id: string, name: string, data: Record<string, any>): StepRecord {}`
    - [x] For arrays of objects: `table(id: string, name: string, headers: Record<string, string>, rows: Record<string, any>[]): StepRecord {}`
    - [x] For binary data: `binary(id: string, name: string, mimeType: string, data: string | Uint8Array): StepRecord {}`
  - [x] The `pass`, `fail`, and `error` methods should be updated to take a third, optional argument of type `StepRecord[]`, which should be added to the response.
  - [x] ExpectedRecord handling:
    - [x] There should be a new `ExpectedRecord` interface exported in `base-step.ts` (see linked Pardot example commit above)
    - [x] There should be a new, optional expectedRecords protected property on the `BaseStep` class
    - [x] The `BaseStep::getDefinition()` method should set any expected records if provided on the protected property by an implementing step class.

**Comment by amcpanaligan** [comment]
The `opportunity` object has too many properties and the table can no longer contain it.

![image](https://user-images.githubusercontent.com/10269901/75123472-9b84f100-56e2-11ea-8799-f742c4e39910.png)

Maybe we can define which Properties are required to be included in the table view.

**Comment by amcpanaligan** [comment]
Does `Fields returned on the ExpectedRecords definition should always include the following fields: Id, CreatedDate, LastModifiedDate.` Mean that we only return those? Otherwise, let's define something for each `object`

**Comment by iamEAP** [comment]
I suspect it will be difficult/impossible to know which fields will be useful to show vs. which won't, especially at run-time, and especially because people can add whatever custom fields they want to these objects.

Instead, I think we should handle this more on the "display" side (in the CLI) vs. on the Cog side.  We could explore a few options there:

1. Detect when column width might be too wide
2. In such case, write the data to disk
3. Or allow the column data to be truncated on display
4. Or write the data to disk (maybe as a CSV)

Or most likely, some combination of all of the above.
